package com.careerpro.backend.service;

import com.careerpro.backend.ai.GeminiAiClient;
import com.careerpro.backend.ai.PromptTemplateEngine;
import com.careerpro.backend.dto.UserProfileDto;
import com.careerpro.backend.entity.*;
import com.careerpro.backend.exception.ResourceNotFoundException;
import com.careerpro.backend.repository.*;
import com.fasterxml.jackson.databind.JsonNode;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.util.*;
import java.util.stream.Collectors;

@Slf4j
@Service
@RequiredArgsConstructor
public class CareerRecommendationService {

    private final GeminiAiClient geminiClient;
    private final PromptTemplateEngine promptEngine;
    private final UserRepository userRepository;
    private final UserProfileRepository userProfileRepository;
    private final UserSkillRepository userSkillRepository;
    private final CareerRecommendationRepository recommendationRepository;
    private final CareerResultRepository careerResultRepository;
    private final NotificationRepository notificationRepository;
    private final UserProfileService userProfileService;

    @Transactional
    public List<CareerRecommendation> generateRecommendations(Long userId) {
        // Fetch user data
        UserProfileDto profile = userProfileService.getProfile(userId);
        List<UserSkill> skills = userSkillRepository.findByUserId(userId);

        // Get dominant interest
        String dominantInterest = careerResultRepository
                .findTopByUserIdOrderByTestDateDesc(userId)
                .map(CareerResult::getDominantCategory)
                .orElse("Technology");

        // Build prompt
        String prompt = promptEngine.buildCareerRecommendationPrompt(profile, skills, dominantInterest);

        // Call Gemini AI
        String aiResponse = geminiClient.generateContent(prompt);
        log.debug("Career recommendation AI response received");

        // Parse and save recommendations
        List<CareerRecommendation> recommendations = parseAndSaveRecommendations(userId, aiResponse);

        // Send notification
        User user = userRepository.findById(userId).orElseThrow();
        createNotification(user, "🎯 Career Recommendations Ready",
                "Your personalized career recommendations have been generated by AI!", "SUCCESS");

        return recommendations;
    }

    @Transactional(readOnly = true)
    public List<CareerRecommendation> getRecommendations(Long userId) {
        return recommendationRepository.findByUserIdOrderByRankOrderAsc(userId);
    }

    @Transactional
    public Map<String, Object> generateSkillGapAnalysis(Long userId, String targetCareer) {
        List<UserSkill> skills = userSkillRepository.findByUserId(userId);

        String prompt = promptEngine.buildSkillGapAnalysisPrompt(skills, targetCareer);
        String aiResponse = geminiClient.generateContent(prompt);

        JsonNode json = geminiClient.parseResponse(aiResponse);
        return geminiClient.getObjectMapper().convertValue(json, Map.class);
    }

    @Transactional
    public Map<String, Object> generateLearningRoadmap(Long userId, String careerTitle) {
        List<CareerRecommendation> recs = recommendationRepository.findByUserIdOrderByRankOrderAsc(userId);

        // Get missing skills from top recommendation
        List<String> missingSkills = new ArrayList<>();
        if (!recs.isEmpty()) {
            String ms = recs.get(0).getMissingSkills();
            if (ms != null && !ms.isEmpty()) {
                missingSkills = Arrays.asList(ms.split(",\\s*"));
            }
        }

        UserProfileDto profile = userProfileService.getProfile(userId);
        String cgpa = profile.getCgpa() != null ? profile.getCgpa().toString() : null;

        String prompt = promptEngine.buildLearningRoadmapPrompt(
                careerTitle, missingSkills, 1, cgpa);

        String aiResponse = geminiClient.generateContent(prompt);

        // Save learning path
        User user = userRepository.findById(userId).orElseThrow();
        LearningPath learningPath = new LearningPath();
        learningPath.setUser(user);
        learningPath.setCareerTitle(careerTitle);
        learningPath.setRoadmapJson(aiResponse);

        // We need to inject LearningPathRepository - done via field
        JsonNode json = geminiClient.parseResponse(aiResponse);
        return geminiClient.getObjectMapper().convertValue(json, Map.class);
    }

    private List<CareerRecommendation> parseAndSaveRecommendations(Long userId, String jsonText) {
        // Delete existing recommendations
        recommendationRepository.deleteByUserId(userId);

        User user = userRepository.findById(userId).orElseThrow();
        List<CareerRecommendation> saved = new ArrayList<>();

        try {
            JsonNode root = geminiClient.parseResponse(jsonText);
            JsonNode recommendations = root.path("recommendations");

            if (!recommendations.isArray()) {
                log.warn("Recommendations not in array format, response: {}", jsonText);
                return saved;
            }

            int rank = 1;
            for (JsonNode rec : recommendations) {
                CareerRecommendation cr = CareerRecommendation.builder()
                        .user(user)
                        .careerTitle(rec.path("careerTitle").asText("Unknown Career"))
                        .confidenceScore(BigDecimal.valueOf(rec.path("confidenceScore").asDouble(75.0)))
                        .reason(rec.path("reason").asText())
                        .requiredSkills(arrayNodeToString(rec.path("requiredSkills")))
                        .missingSkills(arrayNodeToString(rec.path("missingSkills")))
                        .salaryRange(rec.path("salaryRange").asText("₹5 LPA - ₹15 LPA"))
                        .demandLevel(rec.path("demandLevel").asText("High"))
                        .futureScope(rec.path("futureScope").asText())
                        .companiesHiring(arrayNodeToString(rec.path("companiesHiring")))
                        .suggestedProjects(arrayNodeToString(rec.path("suggestedProjects")))
                        .rankOrder(rank++)
                        .build();
                saved.add(recommendationRepository.save(cr));
            }
        } catch (Exception e) {
            log.error("Error parsing career recommendations: {}", e.getMessage());
            // Return fallback
            CareerRecommendation fallback = CareerRecommendation.builder()
                    .user(user)
                    .careerTitle("Software Developer")
                    .confidenceScore(BigDecimal.valueOf(80.0))
                    .reason("Based on your profile, software development is a strong match")
                    .salaryRange("₹5 LPA - ₹20 LPA")
                    .demandLevel("Very High")
                    .rankOrder(1)
                    .build();
            saved.add(recommendationRepository.save(fallback));
        }

        return saved;
    }

    private String arrayNodeToString(JsonNode node) {
        if (node == null || node.isNull() || !node.isArray()) return "";
        List<String> items = new ArrayList<>();
        node.forEach(n -> items.add(n.asText()));
        return String.join(", ", items);
    }

    private void createNotification(User user, String title, String message, String type) {
        Notification notification = Notification.builder()
                .user(user)
                .title(title)
                .message(message)
                .type(type)
                .build();
        notificationRepository.save(notification);
    }
}
